version: "3.8"

services:
    # mysql:
    #     image: mysql:8.0
    #     container_name: mysql
    #     restart: unless-stopped
    #     environment:
    #         MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    #         MYSQL_DATABASE: ${DB_DATABASE}
    #     ports:
    #         - 3306:3306
    #     volumes:
    #         - ./mysql:/var/lib/mysql
    #     networks:
    #         - database-network
    #     command: --default-authentication-plugin=mysql_native_password

    mariadb:
        image: mariadb:11.3
        container_name: mariadb
        restart: unless-stopped
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MARIADB_DATABASE: ${DB_DATABASE}
        ports:
            - 3306:3306
        volumes:
            - ./mariadb:/var/lib/mariadb
        networks:
            - database-network
        command: --default-authentication-plugin=mysql_native_password

    # postgresql:
    #     image: postgres:14
    #     container_name: postgresql
    #     restart: unless-stopped
    #     environment:
    #         POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
    #         POSTGRES_DB: ${DB_DATABASE}
    #     ports:
    #         - 5432:5432
    #     volumes:
    #         - ./postgresql:/var/lib/postgresql/data
    #     networks:
    #         - database-network

    # mssql:
    #     image: mcr.microsoft.com/mssql/server:2022-latest
    #     container_name: mssql
    #     restart: unless-stopped
    #     environment:
    #         SA_PASSWORD: ${DB_ROOT_PASSWORD}
    #         ACCEPT_EULA: "Y"
    #     ports:
    #         - 1433:1433
    #     volumes:
    #         - ./mssql:/var/opt/mssql
    #     networks:
    #         - database-network

    # mongodb:
    #     image: mongo:5.0
    #     container_name: mongodb
    #     restart: unless-stopped
    #     environment:
    #         MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
    #         MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    #     ports:
    #         - 27017:27017
    #     volumes:
    #         - ./mongodb:/data/db
    #     networks:
    #         - database-network

    # redis:
    #     image: redis:7.2.4
    #     container_name: redis
    #     restart: unless-stopped
    #     environment:
    #         REDIS_PASSWORD: ${DB_ROOT_PASSWORD}
    #     ports:
    #         - 6379:6379
    #     volumes:
    #         - ./redis:/data
    #     networks:
    #         - database-network
    #     command: redis-server --requirepass ${DB_ROOT_PASSWORD}

volumes:
    #mysql:
    mariadb:
    #postgresql:
    #mssql:
    #mongodb:
    #redis:

networks:
    database-network:
        driver: bridge
